#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh --colorblocks
##$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

## Custom Rules

## bspc config focused_border_color "#99ccff"
## bspc config focused_border_color "#2D3586"
## bspc config focused_border_color "#1976D2"
bash ~/scripts/autobspwm.sh

## End of Custom Rules

#old=2
bspc config border_width         4
bspc config window_gap          35

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## Set a wallpaper
feh --bg-scale ~/wallpapers/rainy.jpg --bg-scale ~/wallpapers/tree.jpg
##feh --bg-scale ~/wallpapers/rainy.jpg
